spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kevinpalma20/bootcamp2021-server-config-properties.git
          username: kevinpalma20
          password: poolstar123
          default-label: main

server:
  port: 9510
